# Generated by Django 5.2.10 on 2026-01-28 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Attendance date')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], help_text='Attendance status (Present/Absent)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee reference', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_set', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance_attendance',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['employee'], name='attendance__employe_c89dc0_idx'), models.Index(fields=['date'], name='attendance__date_61f2e1_idx'), models.Index(fields=['status'], name='attendance__status_132c06_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
