# Generated by Django 5.2.10 on 2026-01-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, help_text='Unique employee identifier', max_length=20, unique=True)),
                ('full_name', models.CharField(help_text='Full name of the employee', max_length=100)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('department', models.CharField(help_text='Department name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees_employee',
                'ordering': ['employee_id'],
            },
        ),
    ]
